jobs:
  ci:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Get Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./main/check

name: Action

on:
  schedule:
    - cron: "40 */6 * * *"
